baseurl = "http://guatemalajs.org"
title = "GuatemalaJS"
theme="material-design"
languageCode = "en-us"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "guatemalajs" # optional
copyright = "© 2015 Copyright JumLabs"

[params]
  description = "GuatemalaJS Site" # optional
  # twitter = "Your Twitter Name" # optional
  github = "guatemalajs" # optional
  facebook = "guatemalajs" # optional
  # gplus = "Your Google+ profile name" # optional
  # linkedin = "Your LinkedIn Name" # optional
  headerCover = "images/headerCover.png" # optional
  footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "UA-71498851-2" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
